### PR TITLE
WIP: graphex "backend" - cabal & ghc integration

### PR DESCRIPTION
**Pull request by ramirez7**
This CLI uses the Looking Glass JSON format from [my `graphmod` fork.](https://github.com/ramirez7/graphmod)

I thought it made sense to fold the functionality from `graphmod` (using cabal to find files + parsing out imports) into `graphex`.

We can use GHC's parser proper too.

I also included some Nix stuff, but [I'm not getting cache hits from haskell.nix for some reason.](https://github.com/input-output-hk/haskell.nix/issues/2012) I've included the cabal freeze file since I've just been using straight cabal.

---------------

- [x] Bring in `graphmod` cabal stuff
- [x] Parse with `ghc-lib-parser`.
  - This is a little overkill, but I had never used the GHC API before so it felt like a good chance to poke around. 
- [x] Build the graph (`Map ModuleName (Set ModuleName)`)
- [ ] Make `Module` have name (as a list), filepath, and package for maximum clarity.
- [ ] [Re-implement deps_of](https://github.com/ramirez7/graphmod/blob/bb71748f87c127f86e6f5a95db78df366cb792c8/src/Graphmod.hs#L664-L681)
- [x] `graphex select` looks like what `deps_on` was going to be
- [ ] Re-implement `graphmod`'s ability to exclude modules
- [ ] Graphviz output
- [ ] [Gephi-compatible output](https://gephi.org/users/supported-graph-formats/csv-format/(
- [x] Looking Glass output
  - [ ] Add ability to highlight sub-graph within a larger one
- [ ] Avoid/fix [this `graphmod` bug.](https://github.com/yav/graphmod/issues/41)

### CODE REVIEW

**Comment by dustin** [comment]
Neat, I should do a CI builder thing real quick.

**Comment by dustin** [comment]
I think you can start pushing if you'd like.

For a bit, this was pretty good at demonstrating some graph algorithms and quickcheck stuff, but it's probably better if it's a more generally useful tool for looking at Haskell module dependencies.

**Comment by ramirez7** [comment]
I think we can keep both. The general graph CLI stuff you've made is useful for more than Haskell. But obvious the main source of data we are using it on is Haskell packages.

**Comment by ramirez7** [comment]
I'm gonna clean this up a _little_ more (some unit tests for import parsing would be nice) and merge today. Here's what's changed:

- No more `ghc-lib-parser`. I wrote a quick and dirty import parser with `megaparsec` that seems to work.
- I've reworked the CLI:
  - The existing CLI is now a subcommand: `graph`.
  - I've added a `cabal` subcommand that looks for a cabal file in pwd and outputs a Looking Glass JSON (the format `graph` understands) for your internal dependencies.

**Comment by ramirez7** [comment]
Okay, I made some issues for stuff I didn't get to + some ideas I had. This seems to work (tested it on a few repos) - both the visualizations + the `graph` subcommands.

**Comment by dustin** [comment]
Woo!  Thanks.

**Pull request merged**
